cut_log: false
cut_first_n_line: 2
cut_last_n_line: 10
data_dir: ../_AutpPrep3_out/_data
debug: true
diverse_input: false
env_url: http://10.37.113.98:6138
execute_mode: rule
filecachedir: ./_tmp
gen_tbl_cut_col: 8
gen_tbl_cut_line: 5
git_local_repo: /home/fanmeihao/projects/AutoPrep2
ini_tbl_cut_col: 20
ini_tbl_cut_line: 20
line_limit: false
max_debug_round_container_op: 3
max_debug_round_local_op: 3
max_file_cnt: 30
max_input_limit: 35960
max_output_limit: 4096
nl2sql_data_dir: /home/fanmeihao/data/SkyRL
openai_base_url: https://ark-cn-beijing.bytedance.net/api/v3
parallel: true
print_key: false
proxy: http://sys-proxy-rd-relay.byted.org:8118
record_log: false
server_name: dev
temperature: 0.01
tmp_dir: ./_tmp
total_benchmarks:
- LongDA
- KramaBench
version: 0.0.1
