agent_max_err_cnt: 3
cut_first_n_line: 2
cut_last_n_line: 10
cut_log: false
data_dir: /mnt/vdc_5t/data/autoprep2
debug: true
env_url: http://192.168.2.7:6138
proxy: http://100.68.170.171:3128
execute_mode: rule
tmp_dir: ./_tmp
gen_tbl_cut_col: 8
gen_tbl_cut_line: 5
git_local_repo: /mnt/vdb_1t/project/AutoPrep2
ini_tbl_cut_col: 20
ini_tbl_cut_line: 20
line_limit: false
max_debug_round_container_op: 3
max_debug_round_local_op: 3
max_file_cnt: 30
max_input_limit: 35960
max_output_limit: 4096
nl2sql_data_dir: /mnt/vdc_5t/data/SkyRL
openai_base_url: https://ark.cn-beijing.volces.com/api/v3
parallel: true
print_key: false
record_log: false
temperature: 0.01
version: 3.0.2
diverse_input: false
total_benchmarks:
- LongDA
- KramaBench
version: 0.0.0